# ----------------- hyprland conf -------------------------------

# env
source = ~/.config/hypr/conf/env.conf

# Monitor
source = ~/.config/hypr/conf/monitor.conf

# Autostart
source = ~/.config/hypr/conf/autostart.conf

# Keyboard binds
source = ~/.config/hypr/conf/bind.conf

# Keyboard
source = ~/.config/hypr/conf/keyboard.conf

# Animation
source = ~/.config/hypr/conf/animation.conf

# Window rules
source = ~/.config/hypr/conf/windowrules.conf

# Misc
source = ~/.config/hypr/conf/misc.conf


# Custom config of user
source = ~/.config/hypr/conf/local.conf


# Quickshell user
source = ~/.config/hypr/conf/quickshell.conf

# ---------------------------------------------------------------