# -----------------------------------------------------------

windowrule = float on, size 1070 700, match:class kitty
windowrule = float on, size 870 660, match:class org.quickshell
windowrule = float on, size 750 450, match:class blueman-manager
windowrule = float on, size 750 450, match:class org.pulseaudio.pavucontrol
windowrule = float on, size 1050 710, match:class pcmanfm-qt
windowrule = float on, size 600 400, match:class nm-connection-editor
windowrule = float on, size 900 700, match:class waypaper
windowrule = float on, size 1300 900, match:class peazip

# -----------------------------------------------------------